version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5

    working_directory: ~/event-reminder

    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          command: |
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1